config/routes.rb
Hnclone::Application.routes.draw do
  get "votes/create"

  get "users/new"

  get "users/index"

  root :to => 'stories#index'
  resources :stories do
    resources :votes, :only => [:create]
  end

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :comments, only: [:create, :show] do
    resources :votes, :only => [:create]
  end

  resources :votes, only: [:create]

  match '/signup' => 'users#new'
  match '/signin' => 'sessions#new'
  match '/signout' => 'sessions#destroy', via: :delete

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :commentable, :polymorphic => true
  belongs_to :story
  has_many :comments, :as => :commentable
  has_many :votes, :as => :voteable
  has_many :karmas, :as => :karmable
  attr_accessible :body, :user_id, :commentable_type, :commentable_id, :story_id
end

app/models/karma.rb
class Karma < ActiveRecord::Base
  attr_accessible :author_id, :user_id, :karmable_id, :karmable_type
  belongs_to :user
  belongs_to :author, :class_name => "User"
  belongs_to :karmable, :polymorphic => true

  before_save :add_author_id

  def add_author_id
    self.author_id = self.karmable_type.constantize.find(self.karmable.id).user.id
  end
end

app/models/story.rb
class Story < ActiveRecord::Base
  attr_accessible :title, :url, :user_id
  validates :url, :uniqueness => {:case_sensitive => false,
                                  :message => "That story has already been submitted"}

  belongs_to :user
  has_many :comments, :as => :commentable
  has_many :comments
  has_many :votes, :as => :voteable
  has_many :karmas, :as => :karmable

  scope :joins_with_votes, joins('LEFT OUTER JOIN votes ON stories.id = votes.voteable_id')
  scope :order_by_votes_over_time, order("((CAST(COUNT(votes.id) AS REAL)) / (strftime('%s','NOW') - strftime('%s',stories.created_at))) DESC")

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :first_name, :last_name, :password, :password_confirmation
  has_secure_password

  has_many :stories
  has_many :comments
  has_many :votes
  has_many :karmas
  has_many :karmas_received, :class_name => "Karma", :foreign_key => "author_id"

  before_save {|user| user.email = email.downcase }
  before_save :create_remember_token

  validates :first_name, :presence => { message: "Please enter a first name" }
  validates :last_name, :presence => { message: "Please enter a last name" }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, :presence => { message: "Please enter a valid email" } ,
             :format => { with: VALID_EMAIL_REGEX, message: "Please enter a valid email" },
             :uniqueness => { case_sensitive: false, message: "That email is already registered" }
  validates :password, :presence => { message: "Please enter a password" }, :length => { minimum: 6, message: "Password must be 6 characters"}
  validates :password_confirmation, :presence => { message: "Please confirm your password" }

  def karma_score
    self.karmas_received.length
  end

  private

    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end

end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :voteable, :polymorphic => true
  attr_accessible :value, :user_id, :voteable_id, :voteable_type
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :signed_in_user, only: [:create,:show]
  before_filter :init_vote, only: [:show]
  
  def create
    @comment = Comment.new(params[:comment])
    if @comment.save
      flash[:success] = "Thanks for your comment!"
      redirect_to story_path(@comment.story_id)
    else 
      flash[:alert] = @story.errors.messages
      redirect_to story_path(@comment.story_id)
    end
  end
  
  def show
    @comment = Comment.find_by_id(params[:id])
    @story = Story.find_by_id(@comment.story_id)
    @new_comment = Comment.new
  end
  
  private
  
    def init_vote
      @vote = Vote.new
    end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
    
  end
  
  def create
    user = User.find_by_email(params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_to root_path
    else
      render 'new'
    end
  end
  
  def destroy
    sign_out
    redirect_to root_path
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_filter :find_story_by_id, only: [:update, :edit, :show]
  before_filter :signed_in_user , only: [:create, :new, :update, :edit]
  before_filter :authorized_user, only: [:edit, :update]
  before_filter :still_editable, only: [:edit]
  before_filter :init_vote, only: [:index, :show]

  def create
    @story = Story.new(params[:story])
    if @story.save
      flash[:success] = "Thanks for sharing!"
      redirect_to stories_path
    else
      flash.now[:alert] = @story.errors.messages
      render "new"
    end
  end

  def new
    @story = Story.new
  end

  def update
    @story.update_attributes(params[:story])
    redirect_to current_user
  end

  def edit

  end

  def index
    @stories = Story.joins_with_votes.group('stories.id').order_by_votes_over_time.page(params[:page]).per(20)
  end

  def show
    @comments = @story.comments
    @comment = Comment.new
  end

  private

    def find_story_by_id
      @story = Story.find_by_id(params[:id])
    end

    def authorized_user
      redirect_to root_path unless @story.user == current_user
    end

    def still_editable
      redirect_to story_path(@story) unless Time.now < @story.created_at + 15.minutes
    end

    def init_vote
      @vote = Vote.new
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :signed_in_user, only: [:show]

  def new
    @user = User.new
  end

  def index
  end
  
  def show
    @stories = current_user.stories
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in @user
      flash[:success] = "Welcome #{@user.first_name}!"
      redirect_to root_path
    else
      flash[:alert] = @user.errors.messages
      redirect_to new_user_path
    end
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  def create
    @vote = Vote.new(params[:vote])
    @vote.save
    Karma.create(params[:karma])
    #redirect_to :back
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    cookies.permanent[:remember_token] = user.remember_token
    self.current_user = user
  end
  
  def current_user=(user)
    @current_user = user
  end
  
  def current_user
    @current_user ||= User.find_by_remember_token(cookies[:remember_token])
  end
  
  def signed_in?
    !current_user.nil?
  end
  
  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end
  
  def signed_in_user
    unless signed_in?
      redirect_to signin_path, notice: "To use HNClone, please sign in."
    end
  end
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
  def show_vote(voteable)
    signed_in? && current_user != voteable.user  && !already_voted?(voteable)
  end

  def can_downvote?
    current_user.karmas_received.length > 100
  end

  def already_voted?(voteable)
    !voteable.votes.where(:user_id => current_user.id ).empty?
  end

  def score(voteable)
    voteable.votes.where(:value => 1).length - voteable.votes.where(:value => -1).length
  end
end

app/views/comments/show.html.erb
<h3><%= @comment.body %></h3>

<%= form_for @new_comment, :url => {:controller => "comments", :action => "create" }, :html => {:class => "span4"} do |f|%>
	<%= f.label "Reply" %>
	<%= f.text_area :body %>

	<%= f.hidden_field :user_id, { :value => current_user.id } %>
	<%= f.hidden_field :commentable_id, { :value => @comment.id } %>
	<%= f.hidden_field :commentable_type, { :value => @comment.class.to_s } %>
	<%= f.hidden_field :story_id, { :value => @story.id } %>
	<br>
	<%= f.submit "Create", :class=>"btn btn-primary" %>	
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hnclone</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="navbar">
	  <div class="navbar-inner">
	    <div class="container">
				<%= link_to "HNClone", root_path, :class => "brand" %>
				<ul class="nav">
				  <li class="active"><%= link_to "New Story", new_story_path %></li>
				</ul>
				<ul class="nav pull-right">
					<% if signed_in? %>

						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">
							<%=@current_user.email %> <b class="caret"></b>
							</a>
							<ul class="dropdown-menu">
								<li><%= link_to "My Stories", current_user %></li>
								<li class="divider"></li>
								<li><%= link_to "Logout", signout_path, method: "delete" %></li>
							</ul>
					<% else %>
						<li><%= link_to "Sign up", signup_path %></li>
						<li><%= link_to "Login", signin_path %></li>					
					<% end %>
				</ul>
	    </div>
	  </div>
	</div>



<div class="container">
	<%= render :partial => 'shared/alerts' %>
	<%= yield %>	
</div>
</body>
</html>

app/views/shared/_alerts.erb
<% if flash[:message] %>
	<div class="alert alert-info">
	  <% flash[:message].each do |attribute, message| %>
			<p><%= message.first %></p>
		<% end %>
	</div>
<% elsif flash[:alert] %>
	<div class="alert alert-error">
	  <% flash[:alert].each do |attribute, message| %>
			<p><%= message.first %></p>
		<% end %>
	</div>
<% elsif flash[:success] %>
	<div class="alert alert-success">
	  <%= flash[:success] %>
	</div>
<% end %>

app/views/shared/_vote.erb
<% if show_vote(commentable) %>
  <% if value == 1 || (value == -1 && can_downvote?) %>
  <!-- = image_link 'path/to/image', polymorphic_path(@votable, commentable), :class => 'downvote' -->
   <%#= link_to votes_path(:vote => { voteable_id: commentable.id, voteable_type: commentable.class.to_s, user_id: current_user.id, value: value }, :karma => { user_id: current_user.id, karmable_id: commentable.id, karmable_type: commentable.class.to_s } ), :action => "create", :method => :post do %>
      <span><i class="icon-thumbs-<%= value > 0? "up": "down" %> <%= commentable.class.to_s %> <%=commentable.id%>"></i></span>
    <%# end %>
  <% end %>
<% end %>

app/views/stories/create.html.erb
<h1>Stories#create</h1>
<p>Find me in app/views/stories/create.html.erb</p>

app/views/stories/edit.html.erb
<h1>Edit Story</h1>
<%= form_for @story, :url => {:action => "update" }, :html => {:class => "span4"} do |f| %>
	<%= f.label :title %>
	<%= f.text_field :title %>
	
	<%= f.label :url %>
	<%= f.text_field :url %>
	
	<%= f.hidden_field :user_id, { :value => current_user.id } %>
	<br>
	<%= f.submit "Save", :class=>"btn btn-primary" %>
<% end %>

app/views/stories/index.html.erb
<h1>Welcome to HNClone!</h1>
<p>Here's a list of all stories:</p>
  <ul>
<% @stories.each do |story| %>
  <li>
    <%= render 'shared/vote', :commentable => story, :value => 1 %>

  <%= link_to story.title, story_path(story) %> |
  <%= link_to story.url, story.url %> |
  [<%= story.votes.length %>] </li>

  <% end %>
  </ul>
  <br>
  <%= paginate @stories %>

app/views/stories/new.html.erb
<h1>New Story</h1>
<p>Submit your link to HNClone</p>
<%= form_for @story, :url => {:action => "create" }, :html => {:class => "span4"} do |f| %>
	<%= f.label :title %>
	<%= f.text_field :title %>
	
	<%= f.label :url %>
	<%= f.text_field :url %>
	
	<%= f.hidden_field :user_id, { :value => current_user.id } %>
	<br>
	<%= f.submit "Create", :class=>"btn btn-primary" %>
<% end %>
	

app/views/stories/show.html.erb
<h1 style="display:inline"><%= @story.title %></h1> [<%= @story.votes.length %>]<%= render 'shared/vote', :commentable => @story, :value => 1  %>
<h2><%= @story.url %></h2>

<% def print_comment(comment) %>
  <% children = comment.comments %>
  <li>
      <%= render 'shared/vote', :commentable => comment, :value => 1  %> <%= render 'shared/vote', :commentable => comment, :value => -1  %>
      <%= comment.user.email %> | <%= comment.body %>
      <%if signed_in? %>
        <%= link_to "Reply", comment_path(comment)%>
      <% else%>
        | <%= link_to "Sign in to comment", signin_path %>
      <% end %>
      [<%= score(comment) %>]
  </li>
  <% if !children.empty? %>
    <ul>
      <% children.each {|child| print_comment(child)} %>
    </ul>
  <% end %>
<% end %>

<% @story.comments.where(:commentable_type => "Story").each do |top_comment|  %>
  <ul><% print_comment(top_comment)%></ul>
<% end %>

<% if signed_in? %>
  <%= form_for @comment, :url => {:controller => "comments", :action => "create" }, :html => {:class => "span4"} do |f|%>
    <%= f.label "Comment" %>
    <%= f.text_area :body %>

    <%= f.hidden_field :user_id, { :value => current_user.id } %>
    <%= f.hidden_field :commentable_id, { :value => @story.id } %>
    <%= f.hidden_field :commentable_type, { :value => @story.class.to_s } %>
    <%= f.hidden_field :story_id, { :value => @story.id } %>
    <br>
    <%= f.submit "Create", :class=>"btn btn-primary" %>
  <% end %>
<% end %>


<!--THE ORIGINAL COMMENT STUF <ul>
<% @comments.each do |comment| %>
<li><%= comment.user.email %> | <%= comment.body %>
<%if signed_in? %>
  <%= link_to "Reply", comment_path(comment)%>
<% else%>
  | <%= link_to "Sign in to comment", signin_path %>
<% end %>
</li>
<% end %>
</ul> -->

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<h1>Sign up</h1>
<p>Enter your details below:</p>

<%= form_for @user, :url => {:action => "create" }, :html => {:class => "span4"} do |f| %>

	<%= f.label :first_name %>
	<%= f.text_field :first_name%>

	<%= f.label :last_name %>
	<%= f.text_field :last_name%>
	
	<%= f.label :email %>
	<%= f.text_field :email%>
	
	<%= f.label :password %>
	<%= f.password_field :password%>
	
	<%= f.label :password_confirmation %>
	<%= f.password_field :password_confirmation %>
	<br>
	<%= f.submit "Sign up!", :class => "btn btn-large btn-primary" %>
	
<% end %>

app/views/users/show.html.erb
<h1> <%= "#{current_user.first_name} #{current_user.last_name}'s submitted stories" %></h1>
<h2> Karma Score : <%= current_user.karma_score %></h2>
<ul>
<% @stories.each do |story| %>
  <li><%= link_to story.title, story.url %> | <%= story.url %> | <%= link_to "Edit", edit_story_path(story.id)%></li>
<% end %>
</ul>